/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CategoriasDAO;

/**
 *
 * @author guilherme
 */
public class ListCategorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListCategorias
     */
    public ListCategorias() {
        initComponents();
    }
    
    public void carregarTabela(){
        List<?> lista;
        DefaultTableModel model = new DefaultTableModel();
        String[] colunas = {"Código", "Nome"};
        if ( rbPF.isSelected()) {
            colunas[6] = "CPF";
            lista = ClienteDAO.getClientesPF();
        }else if(rbPJ.isSelected()){
            colunas[6] = "CNPJ";
            lista = ClienteDAO.getClientesPJ();
        }else{
            lista = ClienteDAO.getClientes();
        }
            
            model.setColumnIdentifiers(colunas);
            
            for (Object cli : lista) {
                Cliente cliente = (Cliente) cli;
                 String receberEmail = "Não";
                    if (cliente.isReceberEmail()) 
                        receberEmail = "Sim";
                    Object[] linha = {};
                
                
                if ( cliente.getTipo().equals( Cliente.PESSOA_FISICA ) ) {
                    ClientePF pf = (ClientePF) cli;
                    
                    
                    linha = new Object[] {
                        pf.getId(), pf.getNome(),
                        pf.getEmail(), receberEmail,
                        pf.getCidade().getNome(), "Pessoa Física",
                        pf.getCpf()};
                   

                }else{
                    
                    ClientePJ pj = (ClientePJ) cli;
                    
                    linha = new Object[] {
                        pj.getId(), pj.getNome(),
                        pj.getEmail(), receberEmail,
                        pj.getCidade().getNome(), "Pessoa Física",
                        pj.getCnpj()};
                    
                }
                
                 model.addRow( linha );
            
        }
        tableClientes.setModel( model );

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();

        setTitle("Lista Categorias");

        btnCancel.setText("Cancelar");
        btnCancel.setToolTipText("");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnCancel)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int linha = tableCategorias.getSelectedRow();
        
        if(linha < 0){
            JOptionPane.showMessageDialog(this, "Você deve selecionar um cliente!");
        }else{
            int id = (int) tableCategorias.getValueAt(linha, 0);
            String nome = (String) tableCategorias.getValueAt(linha, 1);
            int resposta = JOptionPane.showConfirmDialog(this,"Confirma a exclusão do cliente" + nome + "?","Exluir Cliente", JOptionPane.YES_NO_OPTION);
            
            if(resposta == JOptionPane.YES_OPTION){
                CategoriasDAO.excluir(id);
                carregarTabela();
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCategorias;
    // End of variables declaration//GEN-END:variables
}
